//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInInstitution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeInInstitution()
        {
            this.Constraints = new HashSet<Constraint>();
            this.Dialogues = new HashSet<Dialogue>();
            this.EmployeeLimits = new HashSet<EmployeeLimit>();
            this.EmployeeLimits1 = new HashSet<EmployeeLimit>();
            this.EmployeeSchedules = new HashSet<EmployeeSchedule>();
        }
    
        public int employeeInInstitutionId { get; set; }
        public Nullable<int> employeerId { get; set; }
        public Nullable<int> institutionId { get; set; }
        public Nullable<int> fieldOfWorkId { get; set; }
        public string status { get; set; }
        public string shiftType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constraint> Constraints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dialogue> Dialogues { get; set; }
        public virtual FieldOfWorkInInstitution FieldOfWorkInInstitution { get; set; }
        public virtual InstitutionDtail InstitutionDtail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLimit> EmployeeLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLimit> EmployeeLimits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSchedule> EmployeeSchedules { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
