//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionDtail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitutionDtail()
        {
            this.EmployeeInInstitutions = new HashSet<EmployeeInInstitution>();
            this.FieldOfWorkInInstitutions = new HashSet<FieldOfWorkInInstitution>();
            this.ShiftInstitutions = new HashSet<ShiftInstitution>();
        }
    
        public int institutionId { get; set; }
        public string institutionName { get; set; }
        public string institutionAddress { get; set; }
        public string institutionEmail { get; set; }
        public string institutionPhone { get; set; }
        public Nullable<int> institutionManagerId { get; set; }
        public Nullable<int> numOfShift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInInstitution> EmployeeInInstitutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldOfWorkInInstitution> FieldOfWorkInInstitutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftInstitution> ShiftInstitutions { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
