//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dialogue
    {
        public int dialogueId { get; set; }
        public Nullable<int> employeeInInstitutionId { get; set; }
        public string status { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual EmployeeInInstitution EmployeeInInstitution { get; set; }
    }
}
