//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMonthShifts
    {
        public int employeeShiftId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> startShift { get; set; }
        public Nullable<System.DateTime> endShift { get; set; }
    
        public virtual EmployeeDetails EmployeeDetails { get; set; }
    }
}
