//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldOfWorkInInstitution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldOfWorkInInstitution()
        {
            this.EmployeeInInstitution = new HashSet<EmployeeInInstitution>();
        }
    
        public int fieldOfWorkId { get; set; }
        public Nullable<int> institutionId { get; set; }
        public string fieldOfWorkName { get; set; }
        public Nullable<int> numOfFullTimeShift { get; set; }
        public Nullable<int> numOfPartTimeShift { get; set; }
        public Nullable<int> numOfEmployeesInWeeklyShift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInInstitution> EmployeeInInstitution { get; set; }
        public virtual InstitutionDtails InstitutionDtails { get; set; }
    }
}
