//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionDtails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitutionDtails()
        {
            this.EmployeeInInstitution = new HashSet<EmployeeInInstitution>();
            this.FieldOfWorkInInstitution = new HashSet<FieldOfWorkInInstitution>();
            this.Settings = new HashSet<Settings>();
        }
    
        public int institutionId { get; set; }
        public string institutionName { get; set; }
        public string institutionAddress { get; set; }
        public string institutionEmail { get; set; }
        public string institutionPhone { get; set; }
        public Nullable<int> institutionManagerId { get; set; }
        public Nullable<int> numOfShift { get; set; }
    
        public virtual EmployeeDetails EmployeeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInInstitution> EmployeeInInstitution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldOfWorkInInstitution> FieldOfWorkInInstitution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settings> Settings { get; set; }
    }
}
