//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Constraints> Constraints { get; set; }
        public virtual DbSet<Dialogue> Dialogue { get; set; }
        public virtual DbSet<EmployeeDetails> EmployeeDetails { get; set; }
        public virtual DbSet<EmployeeInInstitution> EmployeeInInstitution { get; set; }
        public virtual DbSet<EmployeeLimit> EmployeeLimit { get; set; }
        public virtual DbSet<EmployeeShifts> EmployeeShifts { get; set; }
        public virtual DbSet<FieldOfWorkInInstitution> FieldOfWorkInInstitution { get; set; }
        public virtual DbSet<InstitutionDtails> InstitutionDtails { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<ShiftInstitution> ShiftInstitution { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
