//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int settingId { get; set; }
        public Nullable<int> institutionId { get; set; }
        public Nullable<int> freeDaysNum { get; set; }
        public Nullable<int> freeShiftsNum { get; set; }
    
        public virtual InstitutionDtails InstitutionDtails { get; set; }
    }
}
